services:
  orthanc:
    image: jodogne/orthanc-plugins
    ports:
      - "4242:4242"
      - "8042:8042"
    environment:
      - ORTHANC_NAME=ORTHANC
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
