FROM rust:1.86-alpine3.21 AS builder
RUN apk add musl-dev openssl-dev openssl-libs-static

WORKDIR /app

COPY . .

RUN cargo build --release --locked --features s3 --bin dicom-rst

FROM gcr.io/distroless/cc-debian12 AS runtime
COPY --from=builder /app/target/release/dicom-rst /
ENTRYPOINT ["./dicom-rst"]
