[logging]
level = "info"

[http]
interface = "127.0.0.1"
port = 8080

[dicom]
# The AET of the DICOMweb Adapter. Add this AET to the allowlist of each PACS for authentification.
aet = "DICOM-RST"

[dicom.pacs]

# Example:
# [dicom.pacs."ORTHANC"]
# address = "127.0.0.1:4242"
# max_pool_size = 1