[telemetry]
#sentry = "https://536225a2a8979a2fe1882c06579a4f6b@sentry.ship.ume.de/4"
level = "DEBUG"

[server]
aet = "DICOM-RST"

[server.http]
host = "0.0.0.0"
port = 8080
max-upload-size = 50_000_000 # 50 MB
request-timeout = 60_000 # 1 minute

[[server.dimse]]
host = "0.0.0.0"
port = 7001
aet = "DICOM-RST"

# [[aets]]
# aet = "ORTHANC"
# host = "127.0.0.1"
# port = 4242
# backend = "dimse"
# pool = { size = 16, timeout = 10_000 }
# qido-rs = { timeout = 10_000 }
# stow-rs = { timeout = 30_000 }
# wado-rs = { timeout = 30_000, mode = "concurrent", receivers = ["DICOM-RST"] }
