services:
  dicom-rst:
    image: ghcr.io/umessen/dicom-rst:latest
    ports:
      - "8080:8080"
      - "7001:7001"
    volumes:
      - ./dicom-rst.yaml:/config.yaml:ro
    networks:
      - dimse
  orthanc:
    image: jodogne/orthanc-plugins
    ports:
      - "4242:4242"
      - "8042:8042"
    environment:
      - ORTHANC_NAME=ORTHANC
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
    networks:
      - dimse
networks:
  dimse: